version: "3.8"

services:
  mysql:
    image: mysql:8.0.36
    container_name: learning-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: learning
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

    # MySQL image default command is mysqld; we keep it explicit
    command: [ "mysqld" ]

volumes:
  mysql_data: